<?php
namespace AppBundle\Repository;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
	public function getById($id)
	{
		$query = $this->createQueryBuilder('a')
			->setParameter('id', $id)
			->where('a.id = :id')
			->getQuery();
		return $query->getSingleResult();
	}

	public function getAllArtcicles()
	{
		$query = $this->createQueryBuilder('a')
   				->orderBy('a.datePost', 'DESC')
					->setMaxResults(5)
				  ->getQuery();
		return $query->getResult();
	}

	public function rechercheArticleByParametres($texte)
	{
		$query = $this->createQueryBuilder('a')
					->setParameter('id', $texte)
					->where('a.nom = :texte')
					->orderBy('a.id', 'DESC')
					->getQuery();
		return $query->getResult();
	}

}
