<?php
namespace AppBundle\Repository;
/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
	public function getById($id)
	{
		$query = $this->createQueryBuilder('c')
			->setParameter('id', $id)
			->where('c.id = :id')
			->getQuery();
		return $query->getSingleResult();
	}

	public function getArticles($categorie)
	{
		$query = $this->createQueryBuilder('c')
			->setParameter('category', $category)
			->where('c.category = :category')
			->getQuery();
		return $query->getSingleResult();
	}
}
