<?php
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
	public function getCatById($id)
	{
		$query = $this->createQueryBuilder('categorie')
			->setParameter('id', $id)
			->where('categorie.id = :id')
			->getQuery();
		return $query->getResult();
	}

	public function getArticles($categorie)
	{
		$query = $this->createQueryBuilder('c')
			->setParameter('categorie', $categorie)
			->where('c.categorie = :categorie')
			->orderBy('c.datePost', 'DESC')
			->setMaxResults(10)
			->getQuery();
		return $query->getSingleResult();
	}

	public function getAllCategories()
	{
		$query = $this->createQueryBuilder('c')
				  ->getQuery();
		return $query->getResult();
	}

}
