<?php
namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{

	/**
	* Retourne la liste des commentaires d'un article
	* @param id identifiant du article
	* @return int
	**/
	public function getListComments($id)
	{
		$query = $this->createQueryBuilder('c')
			->setParameter('id', $id)
			->where('c.article = :id')
			->getQuery();

		return $query->getResult();
	}

	/**
  * Retourne le total des commentaires d'un article
  * @param id identifiant du article
  * @return int
  **/
  public function NbTotalComment($id)
  {
    return $this
    ->createQueryBuilder('a')
    ->select('count(a)')
    ->where('a.article=:id')
    ->setParameter('id',$id)
    ->getQuery()
    ->getSingleScalarResult()
    ;
    }

}
