<?php
namespace AppBundle\Repository;
/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTagById($id)
	{
		$query = $this->createQueryBuilder('t')
			->setParameter('id', $id)
			->where('t.id = :id')
			->getQuery();
		return $query->getSingleResult();
	}

	public function getAllTags()
	{
		$query = $this->createQueryBuilder('t')
				  ->getQuery();
		return $query->getResult();
	}

}
