<?php
namespace AppBundle\Repository;
/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
	public function getById($id)
	{
		$query = $this->createQueryBuilder('t')
			->setParameter('id', $id)
			->where('t.id = :id')
			->getQuery();
		return $query->getSingleResult();
	}
}
