# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

        bdd_provider:
            entity:
                class: AppBundle:Membre
                property: email

    encoders:
        AppBundle\Entity\Membre: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        acl:
            anonymous: ~
            # http_basic: ~
            provider: bdd_provider
            form_login:
                login_path: menu_login # affiche le form
                check_path: menu_check # vérification des
                  # identifiants fournis
                default_target_path: indexAdmin # Chemin de redirection
                username_parameter: _email
            logout:
                path:   /logout
                target: /
        pattern:
            # Première méthode (exemple pattern)
            pattern: /indexAdmin
            anonymous: false
            http_basic: ~
            provider: in_memory


    access_control:
        - { path: /indexAdmin, roles: IS_AUTHENTICATED_REMEMBERED }
